[window]
option_as_alt = "OnlyLeft"

opacity = 0.9
blur = true

[font]
size = 12

normal = {family = "FiraCode Nerd Font Mono", style = "Regular"}
bold = {family = "FiraCode Nerd Font Mono", style = "Bold"}
italic = {family = "FiraCode Nerd Font Mono", style = "Italic"}

[env]
TERM = "xterm-256color"

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

[colors.cursor]
cursor = '#c0caf5'
text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#ff899d'
green = '#9fe044'
yellow = '#faba4a'
blue = '#8db0ff'
magenta = '#c7a9ff'
cyan = '#a4daff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'
