[window]
option_as_alt = "OnlyLeft"

[font]
size = 14

normal = {family = "JetBrainsMono Nerd Font Mono", style = "Regular"}
bold = {family = "JetBrainsMono Nerd Font Mono", style = "Bold"}
italic = {family = "JetBrainsMono Nerd Font Mono", style = "Italic"}
bold_italic = {family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic"}

[env]
TERM = "xterm-256color"
